config/routes.rb
Asinexplore::Application.routes.draw do

  # use this line for regular email/password registration
  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :users

  resources :products do
    member do
      get :buy
      get :fetch
    end

    collection do
      get :seed
    end
  end

  resources :searches


  namespace :api, path: "", defaults: { format: :json }, constraints: { subdomain: "api" } do
    resources :products
  end

  get "sitemap.xml" => "home#sitemap", format: :xml, as: :sitemap
  get "robots.txt" => "home#robots", format: :text, as: :robots

  root :to => 'products#index'
end

app/models/search.rb
# == Schema Information
#
# Table name: searches
#
#  id         :integer          not null, primary key
#  keywords   :string(255)
#  min_price  :integer
#  max_price  :integer
#  created_at :datetime
#  updated_at :datetime
#

class Search < ActiveRecord::Base

  def products
    @products ||= find_products
  end

  private

    def find_products
      products = Product.where("name like ?", "%#{keywords}%") if keywords.present?
      # products = products.where("description like ?", "%#{keywords}%") if keywords.present?
      # products = products.where("price >= ?", min_price) if min_price.present?
      # products = products.where("price <= ?", max_price) if max_price.present?
      products
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  skip_authorization_check
  
  def new
    @search = Search.new
  end

  def create
    @search = Search.create!(search_params)
    redirect_to @search
  end

  def show
    @search = Search.find(params[:id])
    @client = ASIN::Client.instance
    resp = @client.search({ Keywords: @search.keywords, SearchIndex: :Books, ResponseGroup: :Small })
    @more_url = resp['ItemSearchResponse']['MoreSearchResultsUrl']
    
    asin = resp['ItemSearchResponse']['Items'][0].asin
    resp = @client.similar(asin, ResponseGroup: :Small, SimilarityType: :Intersection)
    if resp.any?
      related_asins = resp.collect { |p| p.raw.ASIN }

      # see if there are any items we need to pull from Amazon
      @products = Product.where(asin: related_asins)
      existing_asins = @products.pluck(:asin)
      asins_to_fetch = related_asins.delete_if { |a| existing_asins.include?(a) }

      if asins_to_fetch.any?
        conn = Connector.new
        fetched_batch = conn.fetch_batch(asins_to_fetch)
        # @products << fetched_batch
        @products.all.push(*fetched_batch)
      end

      @products
    end

    @products
  end

  def update
  end

  private
    def search_params
      params.require(:search).permit(:keywords, :min_price, :max_price)
    end
end

app/views/searches/index.html.erb
<h1>Search Results</h1>

<%= form_tag products_path, method: :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= button_tag "Search", name: nil %>
  </p>
<% end %>

app/views/searches/new.html.erb
<%= form_for @search do |f| %>
  <p>
    <%= f.label :keywords %>
    <%= f.text_field :keywords %>
  </p>

  <p>
    <%= f.label :min_price, "Price Range" %><br />
    <%= f.text_field :min_price, size: 10 %>
    <%= f.text_field :max_price, size: 10 %>
  </p>
  
  <p>
    <%= f.submit "Search" %>
  </p>
<% end %>

app/views/searches/show.html.erb
<% provide(:title, "#{@search.keywords} books") %>

<h1 class="text-center"><%= "You asked for: #{@search.keywords}" %></h1>

<% if @products.empty? %>
  <h3 class="text-center">Sorry, we couldn't find any, but take a look at the most popular books:</h3>
  <% @products = Product.limit(10) %>
<% end %>

<div id="products-container" class="transitions-enabled centered clearfix">
  <% @products.each do |product| %>
    <div class='product-box shadow rounded'>
      <p>
        <a href="<%= product_path(product) %>">
          <%= image_tag(product.image_url, :class => 'img-polaroid img-fade', :width => 226, :title => product.name) %>
        </a>
      </p>
      <p style="font-size: 1.5em;" class="text-center"><%= link_to "#{product.name}", product_path(product), :title => product.name %></p>
    </div>
  <% end %>
</div>

<h2><%= link_to "Plenty more where that came from...", @more_url, target: "_blank" %></h2>