config/routes.rb
Asinexplore::Application.routes.draw do

  # use this line for regular email/password registration
  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :users

  resources :products do
    member do
      get :buy
      get :fetch
    end

    collection do
      get :seed
    end
  end

  resources :searches


  namespace :api, path: "", defaults: { format: :json }, constraints: { subdomain: "api" } do
    resources :products
  end

  get "sitemap.xml" => "home#sitemap", format: :xml, as: :sitemap
  get "robots.txt" => "home#robots", format: :text, as: :robots

  root :to => 'products#index'
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :asin, presence: true
  validates :name, :presence => true
  validates_numericality_of :price, :allow_nil => false, :greater_than_or_equal_to => 0

  def fetch_info
    asin_client = ASIN::Client.instance
    item = asin_client.lookup(self.asin, ResponseGroup: :Large).first
    product_params = Product.create_params(item)
    self.update_attributes(product_params)
  end

  def self.fetch_batch(asins)
    asin_client = ASIN::Client.instance
    items = asin_client.lookup(asins, ResponseGroup: :Large)
    items
  end

  def self.create_params(item)
    default_url = 'http://www.amazon.com/Best-Sellers-Books-Computer-Programming/zgbs/books/3839/?_encoding=UTF8&camp=1789&tag=carlscorn-20&creative=390957&linkCode=ur2'
    item = item[0] if item.is_a?(Array)

    product_params = {
      asin: item.asin, 
      name: item.raw.ItemAttributes.Title,
      sales_rank: item.sales_rank,
      author: '',
      binding: item.binding,
      ean: item.ean,
      edition: item.edition,
      isbn: item.raw.ItemAttributes.ISBN,
      label: item.label,
      language: 'English',
      manufacturer: item.manufacturer,
      mpn: item.raw.ItemAttributes.MPN,
      page_count: item.page_count,
      part_number: item.part_number,
      product_group: item.product_group,
      product_type_name: item.raw.ItemAttributes.ProductTypeName,
      publication_date: item.publication_date,
      publisher: item.publisher,
      sku: item.raw.ItemAttributes.SKU,
      studio: item.studio,
      url: item.raw.DetailPageURL
    }

    if item.raw.ItemAttributes.ReleaseDate
      product_params[:release_date] = item.raw.ItemAttributes.ReleaseDate
    end

    if item.raw.ItemAttributes.ListPrice
      product_params[:price] = (item.raw.ItemAttributes.ListPrice.Amount.to_d / 100)
    else
      product_params[:price] = 0
    end

    if item.raw.ImageSets.ImageSet.is_a?(Array)
      product_params[:image_url] = item.raw.ImageSets.first[1][0].LargeImage.URL
    else
      product_params[:image_url] = item.raw.ImageSets.ImageSet.LargeImage.URL
    end

    if item.raw.ItemAttributes.Author
      if item.raw.ItemAttributes.Author.kind_of?(Array)
        product_params[:author] = ""
        item.raw.ItemAttributes.Author.each do |a|
          product_params[:author] << a + ", "
        end
        product_params[:author] = product_params[:author][0..-3]
      else
        product_params[:author] = item.raw.ItemAttributes.Author
      end
    end

    if item.raw.OfferSumamry
      prouct_params[:total_new] = item.raw.OfferSummary.TotalNew
      prouct_params[:total_used] = item.raw.OfferSummary.TotalUsed
    end

    if item.raw.EditorialReviews.EditorialReview.is_a?(Array)
      item.raw.EditorialReviews.EditorialReview.each do |review|
        if review.Source == "Product Description"
          product_params[:description] = review.Content
        else
          product_params[:amazon_review] = review.Content
        end
      end
    else
      product_params[:description] = item.raw.EditorialReviews.EditorialReview.Content
    end

    product_params
  end

  def self.create_or_update(product_params)
    product = Product.where("asin = ?", product_params[:asin])
    if product.empty?
      Product.create!(product_params)
    else
      product.first.update_attributes(product_params)
    end
  end
end

app/controllers/api/products_controller.rb
class API::ProductsController < ApplicationController
  def index
    "hello"  
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :initialize_asin, only: [:show, :seed]
  skip_authorization_check #only: [:index, :show, :buy, :search, :seed]

  respond_to :html, :json

  def index
    @products = Product.all.order("RAND()").limit(25)
    respond_with @products
  end

  def buy
    @product = Product.find(params[:id])
    redirect_to @product.url
  end

  def show
    authorize! :show, Product
    @product = Product.find(params[:id])
    @meta_description = @product.description[0..140]

    # grab customer reviews <iframe> url
    resp = @client.lookup(@product.asin, ResponseGroup: :Reviews).first
    @amazon_reviews = resp.raw.CustomerReviews.first[1]

    # grab the items related to the current product
    resp = @client.similar(@product.asin, ResponseGroup: :Small, SimilarityType: :Random)
    if resp.any?
      related_asins = resp.collect { |p| p.asin }

      # see if there are any items we need to pull from Amazon
      @related_products = Product.where(asin: related_asins)
      existing_asins = @related_products.pluck(:asin)
      asins_to_fetch = related_asins.delete_if { |a| existing_asins.include?(a) }

      # create each product we fetched that doesn't already exist
      if asins_to_fetch.any?
        # call to Amazon & return the items from the ItemLookup request
        fetched_items = Product.fetch_batch(asins_to_fetch)
        # loop through the items, create product params, then create/update each item
        [fetched_items].each do |p|
          product_params = Product.create_params(p)
          Product.create_or_update(product_params)
        end
      end
      
      @related_products = Product.all.where("asin IN (?)", existing_asins)
    end
    
    respond_with @product
  end

  def fetch
    @product = Product.find(params[:id])
    @product.fetch_info
    redirect_to @product
  end

  def seed
    # authorize! :manage, Product
    items_to_process = []

    VALID_NODES.shuffle!.each do |n|
      resp = @client.browse_node(n, :ResponseGroup => [:BrowseNodeInfo, :NewReleases, :TopSellers, :MostWishedFor, :MostGifted]).first
      items_to_process  = []

      if resp.raw.TopItemSet
        resp.raw.TopItemSet.each do |set|
          items_to_process.push(*resp.raw.TopItemSet.TopItem.collect(&:ASIN))
        end
      end

      items_to_process = items_to_process.uniq

      puts "\n\n========== \n\n"

      items_to_process.each_slice(10) do |batch|
        fetched_items = Product.fetch_batch(batch)

        fetched_items.each do |p|
          product_params = Product.create_params(p)
          Product.create_or_update(product_params)
        end

        sleep rand() + 0.8
      end
    end

    redirect_to root_path
  end


  def destroy
    authorize! :manage, Product
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Product deleted!" if @product.destroy
    redirect_to root_path
  end

  private

    def initialize_asin
      @client = ASIN::Client.instance
    end

    def product_params
      params.require(:product).permit(:description, :image_url, :name, :price, :sku, :asin)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_image_carousel.html.erb
<div class="container">
  <div class="col-xs-12 col-md-12">
    <h1 class="text-center">Amazon Best Sellers</h1>

    <div class="well" style="height: 400px;">
      <div id="myCarousel" class="carousel slide">
        
        <!-- Carousel items -->
        <div class="carousel-inner">
          <% active_row = "active" %>
          <% @products.each_slice(4) do |batch| %>
            <% unless batch.size < 4 %>
              <div class="item <%= active_row %>">
                <% active_row = "" if active_row == "active" %>
                <div class="row">
                  <% batch.each do |p| %>
                    <div class="col-xs-3 col-sm-3">
                      <a href="<%= product_path(p) %>">
                        <img src="<%= p.image_url %>" alt="<%= p.name %>", title="<%= p.name %>" class="img-responsive img-fade">
                      </a>
                    </div>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>

      <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>

    </div><!--/well-->
  </div>
</div>

app/views/products/index.html.erb
<div class="jumbotron">
  <h1>Hello, world!</h1>
  <p>This is an example to show the potential of an offcanvas layout pattern in Bootstrap. Try some responsive-range viewport sizes to see it in action.</p>
</div>

<%#= render 'products/image_carousel' %>

<div class="row">
  <% @products.each do |product| %>
    <div class="col-xs-4 col-sm-4 col-md-3">
      <!-- <strong><%#= product.name %></strong> -->
      <p class="text-center"><%= link_to(product) do %>
        <% cache product do %>
          <%= image_tag(product.image_url, :class => 'img-fade img-responsive', :alt => "#{product.name}", height: 150) %>
          <% end %>
          <!-- <p><%= number_to_currency(product.price) %></p> -->
        <% end %>
      </p>
      <p></p>
    </div><!--/span-->
  <% end %>
</div><!--/row-->

</div><!--/span

app/views/products/show.html.erb
<% if can? :manage, Product %>
  <p>
    <%= link_to "Fetch", fetch_product_path(@product) %> |
    <%= link_to 'Edit', edit_product_path(@product) %> | 
    <%= link_to "Delete", product_path(@product), data: { confirm: 'Are you sure?' } %>
  </p>
<% end %>

<h1 class="text-center" style="margin-bottom: .5em;"> <%= @product.name %> </h1>

<div class="row-fluid">
  <div id="product-image" class="span5 text-center">
    <a href='<%= buy_product_path(@product) %>' target="_blank", caption='<%= "Buy #{@product.name}" %>', title='<%= "Buy #{@product.name}" %>'>
    <%= image_tag(@product.image_url, :class => 'img-polaroid img-fade', :alt => "#{@product.name}") %>
    </a>

    <div id="product-details" class="text-left">
      <h3 class="text-center">Product Details:</h3>
      
      <p><b>ASIN: </b><%= @product.asin %></p>

      <% if @product.author %>
        <p><b>Author(s):</b> <%= @product.author %></p>
      <% end %>

      <% if @product.binding %>
        <p><b>Binding:</b> <%= @product.binding %></p>
      <% end %>

      <% if @product.ean %>
        <p><b>EAN:</b> <%= @product.ean %></p>
      <% end %>

      <% if @product.edition %>
        <%# TODO: figure out why ordinalize() isn't working %>
        <p><b>Edition:</b> <%= @product.edition %></p>
      <% end %>

      <% if @product.price.to_i > 0 %>
        <p>
          <b>Price:</b>  <%= number_to_currency(@product.price, precision: 2) %>
        </p>
      <% end %>

      <% if @product.isbn %>
        <p><b>ISBN:</b> <%= @product.isbn %></p>
      <% end %>

      <%#
        item_height: r.item_height,
        item_length: r.item_length,
        item_weight: r.item_weight,
        item_width: r.item_width,
      %>

      <% if @product.label %>
        <p><b>Label:</b> <%= @product.label %></p>
      <% end %>

      <% if @product.language %>
        <p><b>Language:</b> <%= @product.language %></p>
      <% end %>

      <% if @product.manufacturer %>
        <p><b>Manufacturer:</b> <%= @product.manufacturer %></p>
      <% end %>

      <% if @product.mpn %>
        <p><b>MPN:</b> <%= @product.mpn %></p>
      <% end %>

      <% if @product.page_count %>
        <p><b>Page Count:</b> <%= @product.page_count %></p>
      <% end %>

      <% if @product.part_number %>
        <p><b>Part #:</b> <%= @product.part_number %></p>
      <% end %>

      <% if @product.product_group %>
        <p><b>Category:</b> <%= @product.product_group %></p>
      <% end %>

      <% if @product.publication_date %>
        <p><b>Publication Date:</b> <%= @product.publication_date %></p>
      <% end %>

      <% if @product.publisher %>
        <p><b>Publisher:</b> <%= @product.publisher %></p>
      <% end %>

      <% if @product.sku %>
        <p><b>SKU:</b> <%= @product.sku %></p>
      <% end %>

      <% if @product.studio %>
        <p><b>Studio:</b> <%= @product.studio %></p>
      <% end %>

      <% if @product.total_new %>
        <p><b>In Stock:</b> <span style="color: #009361;">Oh yeah!</span></p>
      <% end %>
    </div>
  </div>

  <div id="product-description" class="span7">
    <div>
      <%= link_to "View on Amazon".html_safe, buy_product_path(@product), :class => 'btn btn-buyit', style: "margin-bottom: 0em; width: 350px; font-size: 40px; padding: 1em;", :target => "_blank" %>
    </div>
    <div id="description-text" class="text-left", style="margin-top: 1em;">
      <%= @product.description.html_safe %>
    </div>
  </div>
</div>

<div><hr class="sexy_line"></div>

<h2 class="text-center">You may also like:</h2>
<% @related_products.each do |p| %>
  <li><%= link_to p.name, product_path(p) %></li>
<% end %>

<div id="amazon-reviews" class="text-center">
  <h2>Amazon Reviews</h2>
  <iframe src="<%= @amazon_reviews %>">
    <p>Your browser does not support iframes.</p>
  </iframe>
</div>